version: '3'
services:
  gif-generator:
      build: ./gif-generator
      env_file:
          - ./gif-generator/.env
      ports:
          - "8080:8080"
      volumes:
          - ./appdata:/appdata
